// ── Mock data for FK Rajec website ─────────────────────────────────────────

export const mockPlayers = [
  {
    id: "1",
    name: "Tomáš Kováč",
    position: "Brankár",
    jerseyNumber: 1,
    image: "https://i.pravatar.cc/200?u=tomas-kovac",
    age: 28,
    nationality: "SK",
  },
  {
    id: "2",
    name: "Martin Novák",
    position: "Obranca",
    jerseyNumber: 4,
    image: "https://i.pravatar.cc/200?u=martin-novak",
    age: 25,
    nationality: "SK",
  },
  {
    id: "3",
    name: "Lukáš Horváth",
    position: "Obranca",
    jerseyNumber: 5,
    image: "https://i.pravatar.cc/200?u=lukas-horvath",
    age: 22,
    nationality: "SK",
  },
  {
    id: "4",
    name: "Marek Blaho",
    position: "Obranca",
    jerseyNumber: 3,
    image: "https://i.pravatar.cc/200?u=marek-blaho",
    age: 30,
    nationality: "SK",
  },
  {
    id: "5",
    name: "Ján Polák",
    position: "Záložník",
    jerseyNumber: 6,
    image: "https://i.pravatar.cc/200?u=jan-polak",
    age: 24,
    nationality: "SK",
  },
  {
    id: "6",
    name: "Peter Škoda",
    position: "Záložník",
    jerseyNumber: 8,
    image: "https://i.pravatar.cc/200?u=peter-skoda",
    age: 27,
    nationality: "SK",
  },
  {
    id: "7",
    name: "Michal Frano",
    position: "Záložník",
    jerseyNumber: 10,
    image: "https://i.pravatar.cc/200?u=michal-frano",
    age: 26,
    nationality: "SK",
  },
  {
    id: "8",
    name: "Radoslav Kuna",
    position: "Záložník",
    jerseyNumber: 7,
    image: "https://i.pravatar.cc/200?u=radoslav-kuna",
    age: 23,
    nationality: "SK",
  },
  {
    id: "9",
    name: "Dávid Matuš",
    position: "Útočník",
    jerseyNumber: 9,
    image: "https://i.pravatar.cc/200?u=david-matus",
    age: 25,
    nationality: "SK",
  },
  {
    id: "10",
    name: "Róbert Bílik",
    position: "Útočník",
    jerseyNumber: 11,
    image: "https://i.pravatar.cc/200?u=robert-bilik",
    age: 21,
    nationality: "SK",
  },
  {
    id: "11",
    name: "Ondrej Janeček",
    position: "Útočník",
    jerseyNumber: 17,
    image: "https://i.pravatar.cc/200?u=ondrej-janecek",
    age: 29,
    nationality: "SK",
  },
];

export const mockFixtures = [
  {
    id: "f1",
    homeTeam: "FK Rajec",
    awayTeam: "TJ Bytča",
    date: new Date("2026-03-14T15:00:00"),
    venue: "Štadión FK Rajec",
    competition: "5. liga JUH skupina B",
    isHome: true,
  },
  {
    id: "f2",
    homeTeam: "TJ Považská Bystrica",
    awayTeam: "FK Rajec",
    date: new Date("2026-03-21T14:00:00"),
    venue: "Štadión Považská Bystrica",
    competition: "5. liga JUH skupina B",
    isHome: false,
  },
  {
    id: "f3",
    homeTeam: "FK Rajec",
    awayTeam: "FK Raková",
    date: new Date("2026-03-28T15:00:00"),
    venue: "Štadión FK Rajec",
    competition: "5. liga JUH skupina B",
    isHome: true,
  },
  {
    id: "f4",
    homeTeam: "ŠK Lysá pod Makytou",
    awayTeam: "FK Rajec",
    date: new Date("2026-04-04T14:00:00"),
    venue: "Ihrisko Lysá pod Makytou",
    competition: "5. liga JUH skupina B",
    isHome: false,
  },
];

export const mockResults = [
  {
    id: "r1",
    homeTeam: "FK Rajec",
    awayTeam: "ŠK Divíky",
    homeScore: 3,
    awayScore: 1,
    date: new Date("2026-03-07T15:00:00"),
    competition: "5. liga JUH skupina B",
    isHome: true,
    outcome: "WIN" as const,
  },
  {
    id: "r2",
    homeTeam: "FK Šuja",
    awayTeam: "FK Rajec",
    homeScore: 2,
    awayScore: 2,
    date: new Date("2026-02-28T14:00:00"),
    competition: "5. liga JUH skupina B",
    isHome: false,
    outcome: "DRAW" as const,
  },
  {
    id: "r3",
    homeTeam: "FK Rajec",
    awayTeam: "FK Nesluša",
    homeScore: 2,
    awayScore: 0,
    date: new Date("2026-02-21T15:00:00"),
    competition: "5. liga JUH skupina B",
    isHome: true,
    outcome: "WIN" as const,
  },
  {
    id: "r4",
    homeTeam: "TJ Stará Bystrica",
    awayTeam: "FK Rajec",
    homeScore: 1,
    awayScore: 0,
    date: new Date("2026-02-14T14:00:00"),
    competition: "5. liga JUH skupina B",
    isHome: false,
    outcome: "LOSS" as const,
  },
  {
    id: "r5",
    homeTeam: "FK Rajec",
    awayTeam: "FC Dolná Tižina",
    homeScore: 4,
    awayScore: 2,
    date: new Date("2026-02-07T15:00:00"),
    competition: "5. liga JUH skupina B",
    isHome: true,
    outcome: "WIN" as const,
  },
];

export const mockStandings = [
  { position: 1, team: "TJ Bytča", played: 20, won: 14, drawn: 3, lost: 3, goalsFor: 48, goalsAgainst: 22, points: 45, isFkRajec: false },
  { position: 2, team: "FK Rajec", played: 20, won: 12, drawn: 4, lost: 4, goalsFor: 41, goalsAgainst: 26, points: 40, isFkRajec: true },
  { position: 3, team: "FK Raková", played: 20, won: 11, drawn: 3, lost: 6, goalsFor: 37, goalsAgainst: 28, points: 36, isFkRajec: false },
  { position: 4, team: "TJ Považská Bystrica", played: 20, won: 9, drawn: 5, lost: 6, goalsFor: 32, goalsAgainst: 25, points: 32, isFkRajec: false },
  { position: 5, team: "ŠK Lysá pod Makytou", played: 20, won: 9, drawn: 2, lost: 9, goalsFor: 29, goalsAgainst: 31, points: 29, isFkRajec: false },
  { position: 6, team: "FK Šuja", played: 20, won: 7, drawn: 5, lost: 8, goalsFor: 26, goalsAgainst: 30, points: 26, isFkRajec: false },
  { position: 7, team: "TJ Stará Bystrica", played: 20, won: 7, drawn: 3, lost: 10, goalsFor: 24, goalsAgainst: 35, points: 24, isFkRajec: false },
  { position: 8, team: "ŠK Divíky", played: 20, won: 5, drawn: 4, lost: 11, goalsFor: 22, goalsAgainst: 38, points: 19, isFkRajec: false },
  { position: 9, team: "FK Nesluša", played: 20, won: 4, drawn: 3, lost: 13, goalsFor: 18, goalsAgainst: 40, points: 15, isFkRajec: false },
  { position: 10, team: "FC Dolná Tižina", played: 20, won: 3, drawn: 2, lost: 15, goalsFor: 15, goalsAgainst: 47, points: 11, isFkRajec: false },
];

export const mockNews = [
  {
    id: "n1",
    title: "Výhra 3:1 nad ŠK Divíky — Rajec dominoval od prvej minúty",
    slug: "vyhra-3-1-nad-sk-diviaky",
    excerpt: "FK Rajec predviedol presvedčivý výkon na domácom ihrisku a zvíťazil nad ŠK Divíky výsledkom 3:1. Hattrickom sa blysol Dávid Matuš.",
    imageUrl: "https://pixabay.com/get/g2a01ff68505f2b54c54512b0f2c0adf36108a2994b94e6df0cb4e60a8c8301dbbb62ad8f8bb11302b4c9d674f310d86a.jpg",
    publishedAt: new Date("2026-03-07T18:00:00"),
    author: "Admin FK Rajec",
  },
  {
    id: "n2",
    title: "Letná príprava 2026 — Program tréningov a priateľských zápasov",
    slug: "letna-priprava-2026",
    excerpt: "Vedenie klubu zverejnilo plán letnej prípravy na sezónu 2026/2027. Čaká nás séria priateľských zápasov a sústredenie v Terchovej.",
    imageUrl: "https://pixabay.com/get/g37692b0312241bda441d3c7b0b0dc28b0a5942908443cc03bb6d512a320d534af5bf05646fee23dedd1f140393f5fbeb.jpg",
    publishedAt: new Date("2026-03-03T10:00:00"),
    author: "Admin FK Rajec",
  },
  {
    id: "n3",
    title: "Nový hráč v tíme — Víta Ondreja Jančeka!",
    slug: "novy-hrac-ondrej-janecek",
    excerpt: "FK Rajec s radosťou oznamuje príchod útočníka Ondreja Jančeka. Skúsený hráč prichádza z FK Šuja a posilní ofenzívnu líniu tímu.",
    imageUrl: "https://pixabay.com/get/ge7769dfeff996130642da18ba76e7180af9ad2bb963826529779485a705ccc0390e5f11f8b918d19aa932df3d1aa3bd9.jpg",
    publishedAt: new Date("2026-02-25T09:00:00"),
    author: "Admin FK Rajec",
  },
];

export const mockTrainings = [
  {
    id: "t1",
    title: "Tréning — Kondícia & Taktika",
    description: "Fyzická príprava a taktické cvičenia pred víkendovým zápasom.",
    date: new Date("2026-03-10T17:30:00"),
    location: "Štadión FK Rajec",
    duration: 90,
  },
  {
    id: "t2",
    title: "Tréning — Štandardné situácie",
    description: "Nácvik rohových kopov, priamych kopov a obranných situácií.",
    date: new Date("2026-03-12T17:30:00"),
    location: "Štadión FK Rajec",
    duration: 90,
  },
  {
    id: "t3",
    title: "Predzápasový tréning",
    description: "Ľahký rozcvičovací tréning pred sobotným zápasom.",
    date: new Date("2026-03-13T10:00:00"),
    location: "Štadión FK Rajec",
    duration: 60,
  },
];
